---
editor: 
  markdown: 
    wrap: 72
---

# Les différents objets R {.backgroundTitre}

## Les vecteurs :

-   Objet élémentaire de R, une dimension

-   Ensemble de valeurs, appelées éléments, de même nature (nombres,
    chaînes de caractères, booléens…)

-   Création de vecteurs avec la fonction c() :

`x ← c(TRUE, TRUE, FALSE) is.logical(x)`

`x ← c(8.04, 18.01, 11.05, 14.05) is.numeric(x)`

`x ← c("Chaîne1", "804", "Chaîne3") is.character(x)`

-   Fonctions utiles sur les vecteurs : length(), class(), names(),
    summary(), sort(), head(), tail(), unique()

## Les matrices et arrays :

-   Une matrice est composée d'un ou de plusieurs ***éléments de mêmes
    types***, organisés en ***deux dimensions***.

Une array est composée d'un ou de plusieurs éléments de mêmes types,
organisés en plusieurs dimensions.

-   Création avec les fonctions matrix et array :

`x ← matrix(c(1,2,3,4,5,6), nrow = 2, ncol = 3) création d'une matrice de numériques avec deux lignes et trois colonnes, remplissage par colonne.`

`x ← array (c(1,2,3,4,5,6,7,8), dim=c(2,2,2)) création d'une array de numériques avec trois dimensions, chaque dimension comprenant deux éléments (~ cube)`

-   Fonctions utiles : dim(), nrow(), ncol()

## Les listes et data.frame :

-   Une **data.frame** est composée de vecteurs nommés de tailles égales
    mais pouvant être de types différents.

-   Une **liste** est composée d'objets différents.

-   Création avec les fonctions list() et data.frame() :

`x ← list(c(TRUE, TRUE, FALSE),       1er élément : un vecteur de trois booléens     c(8.04, 18.01, 11.05, 14.05),         2e élément : un vecteur de quatre numériques "804")                                            3e élément : un vecteur d'une chaîne de caractères`

`x ← data.frame(nom=c("Yaël","Luan","Jade"), 1er élément : un vecteur « nom » de trois chaînes de caractères`

`sexe = factor(c("H","F","F"), 2e élément : un vecteur « sexe » de trois chaînes de caractères`

`age = c(5,1,3))                    3e élément : un vecteur « age » de trois numériques`
