---
title: "Formation-R-perfectionnement"
subtitle: "Module Rappels et compléments sur R et RStudio"
date: today
date-format: "DD/MM/YYYY"
author: "SSP/DEMESIS"
description: |
  Support de formation R-perfectionnement : Module Rappels pour les utilisateurs de R au SSM Agriculture
slide-tone: false # for blind readers
chalkboard: false # press the B key to toggle chalkboard
transition: slide
fig-cap-location: bottom
toc: true
toc-title: Sommaire
toc-depth: 1
toc-float: true
# multiplex: true
execute:
  echo: false
  warning: false
  cache: false
editor:
  render-on-save: true
  markdown: 
    wrap: 72
---

## Avant-propos

<br>

Ce diaporama de formation a été rédigé dans le but d'être le support
visuel des formations dispensées au
[SSM Agriculture](https://agreste.agriculture.gouv.fr/).

Ces formations s'adressent à des agents qui ont suivi [la formation R initiation][https://ssm-agriculture.github.io/formation-R-initiation/] ou qui sont familiers des outils de manipulation de données (dplyr).\

## Avant-propos

Elles sont données en présentiel sur une durée **de 3 jours**, les
modules de cette formation sont ajustables suivants le choix des agents.

::: callout-note
## Champ couvert par cette formation

**Ce support couvre les rappels et compléments sur R et l'environnement
du SSM Agriculture.**

Pour information, les modules de la formation R-perfectionnement sont:

-   01 - Module Rappels

-   02 - Module Fonctions

-   03 - Module Cartes statiques et interactives

-   04 - Module Création de graphiques avec ggplot2

-   05 - Module Quarto

-   06 - Module Parquet

-   07 - Module Initiation à l'écriture d'applications Shiny

Ils sont orientés pour être utile aux agents du SSM Agriculture et se
concentrent sur une utilisation de R via
[RStudio](https://posit.co/download/rstudio-desktop/) qui est mise à
disposition des agents sur la plateforme interne Cerise basée sur
RStudio Workbench.
:::

{{< include 01_Travailler-avec-R-ministere.qmd >}}

{{< include 02_traitement-de-donnees.qmd >}}

{{< include 03_objets.qmd >}}

{{< include 04_indexation.qmd >}}
